version: "3.9"

services:
  # Banco de dados para os usuários
  db-users:
    image: postgres:14
    container_name: ecommerce-db-users
    environment:
      POSTGRES_USER: ecommerce_users
      POSTGRES_PASSWORD: my_password_users
      POSTGRES_DB: ecommerce_users
    networks:
      - ecommerce-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ecommerce_users"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  # Proxy para o banco de usuários
  toxiproxy-users:
    image: ghcr.io/shopify/toxiproxy
    container_name: toxiproxy-users
    depends_on:
      - db-users
    networks:
      - ecommerce-net
    ports:
      - "15432:5432" # Porta para o tráfego do serviço de usuários
      - "8475:8474" # Porta para a API de administração
 
  # Banco de dados para os produtos
  db-products:
    image: postgres:14
    container_name: ecommerce-db-products
    environment:
      POSTGRES_USER: ecommerce_products
      POSTGRES_PASSWORD: my_password_products
      POSTGRES_DB: ecommerce_products
    networks:
      - ecommerce-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ecommerce_products"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  # Proxy para o banco de produtos
  toxiproxy-products:
    image: ghcr.io/shopify/toxiproxy
    container_name: toxiproxy-products
    depends_on:
      - db-products
    networks:
      - ecommerce-net
    ports:
      - "25432:5432"
      - "8476:8474"

  # Banco de dados para os pedidos
  db-orders:
    image: postgres:14
    container_name: ecommerce-db-orders
    environment:
      POSTGRES_USER: ecommerce_orders
      POSTGRES_PASSWORD: my_password_orders
      POSTGRES_DB: ecommerce_orders
    networks:
      - ecommerce-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ecommerce_orders"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  # Proxy para o banco de pedidos
  toxiproxy-orders:
    image: ghcr.io/shopify/toxiproxy
    container_name: toxiproxy-orders
    depends_on:
      - db-orders
    networks:
      - ecommerce-net
    ports:
      - "35432:5432"
      - "8477:8474"

  # Inicialização dos bancos (criação de tabelas e seed)
  db-init:
    build:
      context: .
      dockerfile: services/db-init/Dockerfile
    depends_on:
      db-users:
        condition: service_healthy
      db-products:
        condition: service_healthy
      db-orders:
        condition: service_healthy
    networks:
      - ecommerce-net

  # Serviço de usuários
  users:
    build:
      context: .
      dockerfile: services/users/Dockerfile
    depends_on:
      db-init:
        condition: service_completed_successfully
      toxiproxy-users:
        condition: service_started
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: "postgresql+psycopg2://ecommerce_users:my_password_users@toxiproxy-users:5432/ecommerce_users"
    networks:
      - ecommerce-net

  # Serviço de produtos
  products:
    build:
      context: .
      dockerfile: services/products/Dockerfile
    depends_on:
      db-init:
        condition: service_completed_successfully
      toxiproxy-products:
        condition: service_started
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: "postgresql+psycopg2://ecommerce_products:my_password_products@toxiproxy-products:5432/ecommerce_products"
    networks:
      - ecommerce-net

  # Serviço de pedidos
  orders:
    build:
      context: .
      dockerfile: services/orders/Dockerfile
    depends_on:
      db-init:
        condition: service_completed_successfully
      toxiproxy-orders:
        condition: service_started
    ports:
      - "8003:8003"
    environment:
      DATABASE_URL: "postgresql+psycopg2://ecommerce_orders:my_password_orders@toxiproxy-orders:5432/ecommerce_orders"
    networks:
      - ecommerce-net
      
  locust:
    build:
      context: ./stress_tests
    depends_on:
      - users
      - products
      - orders
    ports:
      - "8089:8089"
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge